package com.jjt.ingsis.printscript.diagnostic

enum class DiagnosticRule {
    UNEXPECTED_CHARACTER,
    UNTERMINATED_STRING,
    INVALID_NUMBER,

    UNEXPECTED_TOKEN,
    INVALID_LITERAL,

    UNDECLARED_VARIABLE,
    UNINITIALIZED_VARIABLE,
    ALREADY_DECLARED_VARIABLE,
    CONSTANT_REASSIGNMENT,
    TYPE_MISMATCH,
    INVALID_BINARY_OPERANDS,
    INVALID_UNARY_OPERAND,
    INVALID_IF_CONDITION,
    INVALID_INPUT_PROMPT,
    INVALID_ENVIRONMENT_VARIABLE_NAME,
    UNSUPPORTED_STATEMENT,
    UNSUPPORTED_EXPRESSION,

    UNKNOWN,
}
